<a href="https://colab.research.google.com/github/RU-Krishna/ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list = ['Krishna', 'Priya', 'Swakshat', 'Prachi']
for index, name in enumerate(list):
  print(f'{index} -> {name}')

0 -> Krishna
1 -> Priya
2 -> Swakshat
3 -> Prachi


In [ ]:
print("Hello World")

Hello World


#NumPy

***NumPy*** stands for Numerical Python.
A package for data analaysis & scientific computing with python.
NumPy uses a multi-dimensional array object, & has functions & tools for working with these arrays.

Matrices in different forms:
1. In python, we call them lists.
2. In NumPy, we call them arrays.
3. in Tensorflow, we call them tensors.

## Array Creation in  NumPy.

### Array from lists.
   To create an array form the list, we pass python list as an argument to the array function of the numpy.

   For example:
   array = np.array([1,2,3,4,5])



In [ ]:
import numpy as np

_1D_array = np.array([1,2,3,4,5,6,7,8,9,10])
_2D_array = np.array([['Krishna', 20, 'BCA'],
                      ['Rds', 20, 'BCA']])
_3D_array = np.array(
    [
        [
            [1,2,3,4,5],
            [6,7,8,9,10]
        ],
        [
            [11,12,13,14,15],
            [16,17,18,19,20]
        ]
    ]
)


print(f'1D array: {_1D_array}\n')
print(f'2D array: {_2D_array}\n')
print(f'3D array: {_3D_array}\n')

1D array: [ 1  2  3  4  5  6  7  8  9 10]

2D array: [['Krishna' '20' 'BCA']
 ['Rds' '20' 'BCA']]

3D array: [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]



## Attributes of numpy Array.

### 1. ndim:
       Provides the dimension of the array.
       For example: array.ndim.
    
### 2. shape:
       It gives the sequence of integers indicating the size of the array for each dimension.
       For example: array.shape

### 3. size:
        It gives the total number of elements in the array.
        For example: array.size
    
### 4. dtype:
        Provides the data type of the elements of the array.
        For example: array.dtype.

### 5. itemsize:
        Size in bytes of each element of the array.
        For example: array.itemsize.

        

In [ ]:
print(f'Dimension of the array: {_1D_array.ndim}, {_2D_array.ndim}, {_3D_array.ndim}\n')

print(f'Shape of the array: {_1D_array.shape}, {_2D_array.shape}, {_3D_array.shape}\n')

print(f'Data Type of the array: {_1D_array.dtype}, {_2D_array.dtype}, {_3D_array.dtype}\n')

print(f'Size of the array: {_1D_array.size}, {_2D_array.size}, {_3D_array.size}\n')

print(f'Item Size of the array: {_1D_array.itemsize}, {_2D_array.itemsize}, {_3D_array.itemsize}\n')

Dimension of the array: 1, 2, 3

Shape of the array: (10,), (2, 3), (2, 2, 5)

Data Type of the array: int64, <U21, int64

Size of the array: 10, 6, 20

Item Size of the array: 8, 84, 8



## Other ways of creating Arrays.

### 1. By specifying data type of the array.
        To do that we specify the dtype argument of the array function.
        For example: np.array([1,2,3], dtype = float)

### 2. Create an array with all zeroes or ones.
       For zeroes: np.zeroes((rows, columns))
       For ones: np.ones((rows, columns))

### 3. To create an array with a given range.
       np.arange(start, stop(exclusive), steps)
       here, arguments are default by definition.

In [ ]:
import numpy as np
dTypeArray = np.array([1,2,3,4,5], dtype = float)

zeroArray = np.zeros((4,5), dtype= int)

onesArray = np.ones((5,6), dtype = int)

range = np.arange(2,20)

range2 = np.arange(2,20,10)


print(f'Dimension Type Array: {dTypeArray}\n')
print(f'Zero Array: {zeroArray}\n')
print(f'Ones Array: {onesArray}\n')
print(f'Range Array without steps declaration: {range}\n')
print(f'Range array with steps declaration: {range2}')



Dimension Type Array: [1. 2. 3. 4. 5.]

Zero Array: [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ones Array: [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

Range Array without steps declaration: [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Range array with steps declaration: [ 2 12]


## Arithmetic Operation on Arrays.

We can perform all the matrix arithmetic operations on arrays.

1. Addition of two arrays: **"array1 + array2"**
2. Subtraction of arrays: **"array1 - array2"**
3. Element wise multiplication: **"array1 * array2"**
4. Matrix Multiplication: **"array1 @ array2"**
5. Exponentiation: **"array1 ** array2"**
6. Division: **"array1 / array2"**
7. Modulo operation: **"array1 % array2"**

In [ ]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
array3 = np.array([[5],[6],[7],[8]])

#Addition
print(array1 + array2)

#Subtraction
print(array2 - array1)

#Element wise multipliation
print(array1 * array2)

#Matrix Mutiplication
print(array1 @ array3)

#Exponentiation
print(array1 ** array2)

#Division
print(array2 / array1)

#Modulo
print(array2 % array1)

[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[70]
[    1    64  2187 65536]
[5.         3.         2.33333333 2.        ]
[0 0 1 0]


In [ ]:
#Transaposition of matrix.

array = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,0,11,12]
    ]
)


print(f'Initial array: \n{array}\n')
print(f'Transposed array: \n{array.transpose()}')

Initial array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0 11 12]]

Transposed array: 
[[ 1  5  9]
 [ 2  6  0]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#Sorting of array.
array = np.array(
    [
        [3,26,56,9],
        [78,25,48,95],
        [69,28,941,36]
    ]
)
print(f'Initial Array: \n{array}\n')
array.sort(axis = 0)
print(f'Sorted Array: \n{array}')

Initial Array: 
[[  3  26  56   9]
 [ 78  25  48  95]
 [ 69  28 941  36]]

Sorted Array: 
[[  3  25  48   9]
 [ 69  26  56  36]
 [ 78  28 941  95]]


In [ ]:
# Array Concatenation

# Remember the dimsension(aixs) along which arrays are concatentating mus be same.

# It mean either both arrays have same rows or same columns.

# aixs = 1 -> rows, axis = 0 -> columns

arrayX = np.array(
    [
        [2,6,8,9],
        [8,2,1,4]
    ]
)

arrayY = np.array(
    [
        [1,1,1,1],
        [2,2,2,2]
    ]
)

print( f'{arrayX.shape}\n{arrayY.shape}')

print(np.concatenate((arrayX, arrayY), axis = 1))

(2, 4)
(2, 4)
[[2 6 8 9 1 1 1 1]
 [8 2 1 4 2 2 2 2]]


In [ ]:
# Reshpaing the array aka changing the dimensions of the array without changing its elements.

array1 = np.array(
    [
        [2,5,3,9],
        [8,9,7,5],
        [0,3,6,0]
    ]
)
print(array1.reshape(1,12))

[[2 5 3 9 8 9 7 5 0 3 6 0]]
